### ISSUE TITLE
API для взаимодействия с таблицей задач.

### ISSUE THREAD

**Issue by EvoFint** [EvoFint/TaskManager#10]
## Get запросы
- [ ] Получение всех задач из доски; #11 
- [ ] Получение задач по фильтру; #12 

## Put запросы
- [ ] Изменение задачи по `id`; #16 

## Post запросы 
- [ ] Создание новой задачи; #15 

## Delete запросы
- [ ] Удаление задачи по `id`; #13
